// SPDX-License-Identifier: AGPL-3.0-or-later
//go:build ignore

// gen-config-docs walks internal/config.ServerConfig via reflection and
// renders docs/reference/configuration.md. The table gives each field's
// YAML path, Go type, default (from DefaultServerConfig), and the env-var
// form SLUICE_X__Y that the viper loader recognises. Run via `make
// docs-generate`; `make docs-check` fails the CI drift gate.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/bino-bi/sluice/internal/config"
)

const header = `<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Generated by scripts/gen-config-docs.go — do not edit by hand. -->

# Configuration

Sluice reads a single ` + "`server.yaml`" + ` at boot plus any number of policy
YAML files under a policies directory. Environment variables prefixed
` + "`SLUICE_`" + ` override individual fields; ` + "`.`" + ` in the YAML path maps to
` + "`__`" + ` in the env name.

` + "```bash" + `
# rest.listen: ':8443' via env override
export SLUICE_REST__LISTEN=:8443
` + "```" + `

## Field reference

The table below is generated from ` + "`internal/config.ServerConfig`" + ` via
reflection. Defaults come from ` + "`DefaultServerConfig()`" + `; every field
can be overridden through the environment using the ` + "`SLUICE_` " + `prefix.

`

const footer = `
## Secrets

All ` + "`*Ref`" + ` / ` + "`genesis`" + ` / ` + "`token`" + ` fields accept a ` + "`secret://<provider>/<path>`" + `
URI. The MVP providers are:

- ` + "`secret://env/NAME`" + ` — read from the process environment.
- ` + "`secret://file/PATH`" + ` — read from a file (permission-checked; 0o022
  rejected, world-readable warned).

Vault, AWS SM, and GCP SM land behind build tags in v0.3+; until then those
references are rejected at config validation / boot.

## Reference schema

` + "`sluice schema export`" + ` emits a JSON Schema 2020-12 document covering
every policy object; server-level settings live in ` + "`server.yaml`" + ` and are
documented above.

## Regenerating

` + "```bash" + `
make docs-generate
` + "```" + `

Walks ` + "`internal/config.ServerConfig`" + ` via reflection so this page tracks
every new field the moment it lands. The drift gate in ` + "`docs-deploy.yaml`" + `
fails when the committed file differs from the generator's output.
`

func main() {
	out := flag.String("out", "docs/reference/configuration.md", "output path")
	check := flag.Bool("check", false, "fail instead of write when output differs")
	flag.Parse()

	defaults := config.DefaultServerConfig()
	defT := reflect.TypeOf(defaults)
	defV := reflect.ValueOf(defaults)

	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("| YAML path | Type | Default | Env var |\n")
	buf.WriteString("| --------- | ---- | ------- | ------- |\n")

	walkConfig(&buf, defT, defV, "")

	buf.WriteString(footer)

	abs, err := filepath.Abs(*out)
	if err != nil {
		fatal("resolve path: %v", err)
	}

	if *check {
		cur, err := os.ReadFile(abs)
		if err != nil {
			fatal("read existing: %v", err)
		}
		if !bytes.Equal(cur, buf.Bytes()) {
			fmt.Fprintln(os.Stderr, "configuration.md drift: run `make docs-generate`")
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(abs, buf.Bytes(), 0o644); err != nil {
		fatal("write %s: %v", abs, err)
	}
	fmt.Printf("wrote %s\n", abs)
}

// walkConfig emits one row per leaf (non-struct) field and recurses into
// nested structs. Field order mirrors source declaration order, keeping the
// generated table readable top-down.
func walkConfig(buf *bytes.Buffer, t reflect.Type, v reflect.Value, prefix string) {
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return
		}
		t = t.Elem()
		v = v.Elem()
	}
	if t.Kind() != reflect.Struct {
		return
	}

	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}

		name := mapstructureName(f)
		if name == "" || name == "-" {
			continue
		}

		path := name
		if prefix != "" {
			path = prefix + "." + name
		}

		ft := f.Type
		fv := v.Field(i)

		// Recurse into struct / *struct fields. Pointer structs only
		// recurse when non-nil to avoid spurious zero defaults in the
		// output (e.g. *TLSConfig is nil by default).
		if ft.Kind() == reflect.Struct {
			walkConfig(buf, ft, fv, path)
			continue
		}
		if ft.Kind() == reflect.Ptr && ft.Elem().Kind() == reflect.Struct {
			// Emit a summary row for optional sections so the reader
			// sees the path even when the default is nil, then recurse
			// if a default is populated.
			fmt.Fprintf(buf, "| `%s` | `%s?` | _unset_ | `%s` |\n",
				path, shortTypeName(ft.Elem()), envName(path))
			if !fv.IsNil() {
				walkConfig(buf, ft.Elem(), fv.Elem(), path)
			}
			continue
		}

		fmt.Fprintf(buf, "| `%s` | `%s` | %s | `%s` |\n",
			path, shortTypeName(ft), formatDefault(fv), envName(path))
	}
}

func mapstructureName(f reflect.StructField) string {
	tag := f.Tag.Get("mapstructure")
	if tag == "" {
		return strings.ToLower(f.Name)
	}
	parts := strings.Split(tag, ",")
	return parts[0]
}

func envName(path string) string {
	// viper uses `.` → `__` per server.go (strings.NewReplacer).
	return "SLUICE_" + strings.ToUpper(strings.ReplaceAll(path, ".", "__"))
}

func shortTypeName(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Ptr:
		return shortTypeName(t.Elem()) + "?"
	case reflect.Slice, reflect.Array:
		return "[]" + shortTypeName(t.Elem())
	case reflect.Map:
		return "map[" + shortTypeName(t.Key()) + "]" + shortTypeName(t.Elem())
	}
	if t.Name() != "" {
		return t.Name()
	}
	return t.String()
}

// formatDefault renders a default value in a single table cell. Empty
// strings and zeros stay visible (` `` `), non-zeros are fenced as code.
func formatDefault(v reflect.Value) string {
	if !v.IsValid() {
		return "`` ``"
	}
	switch v.Kind() {
	case reflect.String:
		s := v.String()
		if s == "" {
			return "`\"\"`"
		}
		return "`" + s + "`"
	case reflect.Bool:
		return fmt.Sprintf("`%t`", v.Bool())
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		// Detect time.Duration by type name so values render as "30s"
		// rather than "30000000000".
		if v.Type().String() == "time.Duration" {
			return fmt.Sprintf("`%s`", v.Interface())
		}
		return fmt.Sprintf("`%d`", v.Int())
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return fmt.Sprintf("`%d`", v.Uint())
	case reflect.Float32, reflect.Float64:
		return fmt.Sprintf("`%g`", v.Float())
	case reflect.Slice, reflect.Array:
		if v.Len() == 0 {
			return "`[]`"
		}
		return fmt.Sprintf("`%v`", v.Interface())
	case reflect.Map:
		if v.Len() == 0 {
			return "`{}`"
		}
		return fmt.Sprintf("`%v`", v.Interface())
	case reflect.Ptr:
		if v.IsNil() {
			return "_unset_"
		}
		return formatDefault(v.Elem())
	}
	return fmt.Sprintf("`%v`", v.Interface())
}

func fatal(f string, args ...any) {
	fmt.Fprintf(os.Stderr, f+"\n", args...)
	os.Exit(1)
}
