// SPDX-License-Identifier: AGPL-3.0-or-later
//go:build ignore

// gen-metrics-docs walks the internal packages and extracts every
// telemetry.Define{Counter,Histogram,Gauge} call via go/ast. The resulting
// catalogue renders into docs/reference/metrics.md, grouped by subsystem
// and sorted by metric name. Source extraction (rather than a live
// prometheus gather) means the generator is deterministic, cgo-free, and
// independent of process state. Run via `make docs-generate`; `make
// docs-check` fails the CI drift gate.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

type metricDecl struct {
	Name    string
	Type    string
	Help    string
	Labels  []string
	Package string
	File    string
}

const header = `<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Generated by scripts/gen-metrics-docs.go — do not edit by hand. -->

# Metrics

Sluice exports Prometheus metrics on ` + "`/metrics`" + ` from the admin port
(default ` + "`:9091`" + `). Metric names follow ` + "`sluice_<subsystem>_<metric>`" + `
and use ` + "`_total`" + ` / ` + "`_seconds`" + ` / ` + "`_bytes`" + ` Prometheus suffixes.

The table below is generated by walking every
` + "`telemetry.Define{Counter,Histogram,Gauge}`" + ` call in the source tree, so
adding a metric anywhere under ` + "`internal/`" + ` surfaces here automatically.

## Process

` + "`sluice_build_info`" + ` is registered by ` + "`internal/telemetry.Init`" + ` with
labels ` + "`version, commit, go, platform, parser, instance, environment`" + `.
It does not appear in the source-driven table below because it is built
directly on the prometheus client rather than via ` + "`telemetry.Define*`" + `.

## Source-derived catalogue

`

const footer = `
## Regenerating

` + "```bash" + `
make docs-generate
` + "```" + `

Parses every ` + "`.go`" + ` file under ` + "`internal/`" + ` and ` + "`pkg/`" + ` with
` + "`go/ast`" + ` and collects ` + "`telemetry.Define{Counter,Histogram,Gauge}`" + `
calls. The drift gate in ` + "`docs-deploy.yaml`" + ` fails when the committed
file differs from the generator's output.
`

func main() {
	out := flag.String("out", "docs/reference/metrics.md", "output path")
	check := flag.Bool("check", false, "fail instead of write when output differs")
	flag.Parse()

	roots := []string{"internal", "pkg"}
	var metrics []metricDecl
	for _, r := range roots {
		ms, err := walkTree(r)
		if err != nil {
			fatal("walk %s: %v", r, err)
		}
		metrics = append(metrics, ms...)
	}

	slices.SortStableFunc(metrics, func(a, b metricDecl) int {
		if c := strings.Compare(a.Package, b.Package); c != 0 {
			return c
		}
		return strings.Compare(a.Name, b.Name)
	})

	var buf bytes.Buffer
	buf.WriteString(header)

	// Group by subsystem (== the package name); emit one table per group
	// so the operator can jump to "audit" or "policy" visually.
	groups := groupBy(metrics, func(m metricDecl) string { return m.Package })
	for _, pkg := range sortedKeys(groups) {
		fmt.Fprintf(&buf, "### %s\n\n", pkg)
		buf.WriteString("| Metric | Type | Labels | Help |\n")
		buf.WriteString("| ------ | ---- | ------ | ---- |\n")
		for _, m := range groups[pkg] {
			labels := "—"
			if len(m.Labels) > 0 {
				labels = "`" + strings.Join(m.Labels, "`, `") + "`"
			}
			fmt.Fprintf(&buf, "| `%s` | %s | %s | %s |\n",
				m.Name, m.Type, labels, escapePipe(m.Help))
		}
		buf.WriteString("\n")
	}

	buf.WriteString(footer)

	abs, err := filepath.Abs(*out)
	if err != nil {
		fatal("resolve path: %v", err)
	}

	if *check {
		cur, err := os.ReadFile(abs)
		if err != nil {
			fatal("read existing: %v", err)
		}
		if !bytes.Equal(cur, buf.Bytes()) {
			fmt.Fprintln(os.Stderr, "metrics.md drift: run `make docs-generate`")
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(abs, buf.Bytes(), 0o644); err != nil {
		fatal("write %s: %v", abs, err)
	}
	fmt.Printf("wrote %s (%d metrics across %d packages)\n", abs, len(metrics), len(groups))
}

// walkTree parses every non-test .go file under root and collects
// telemetry.Define* call sites.
func walkTree(root string) ([]metricDecl, error) {
	var out []metricDecl
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		ms, err := parseFile(path)
		if err != nil {
			return err
		}
		out = append(out, ms...)
		return nil
	})
	return out, err
}

func parseFile(path string) ([]metricDecl, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}

	pkg := f.Name.Name
	var out []metricDecl
	ast.Inspect(f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		x, ok := sel.X.(*ast.Ident)
		if !ok {
			return true
		}

		if x.Name == "telemetry" {
			if m, ok := decodeTelemetryCall(sel.Sel.Name, call.Args, pkg, path); ok {
				out = append(out, m)
			}
			return true
		}
		if x.Name == "prometheus" {
			if m, ok := decodePrometheusCall(sel.Sel.Name, call.Args, pkg, path); ok {
				out = append(out, m)
			}
			return true
		}
		return true
	})
	return out, nil
}

// decodeTelemetryCall handles telemetry.Define{Counter,Histogram,Gauge}
// call signatures: (name, help, labels, [buckets]).
func decodeTelemetryCall(fn string, args []ast.Expr, pkg, path string) (metricDecl, bool) {
	var kind string
	switch fn {
	case "DefineCounter":
		kind = "counter"
	case "DefineHistogram":
		kind = "histogram"
	case "DefineGauge":
		kind = "gauge"
	default:
		return metricDecl{}, false
	}
	if len(args) < 3 {
		return metricDecl{}, false
	}
	name, ok := stringLiteral(args[0])
	if !ok {
		return metricDecl{}, false
	}
	help, _ := stringLiteral(args[1])
	return metricDecl{
		Name: name, Type: kind, Help: help,
		Labels: stringSliceLiteral(args[2]),
		Package: pkg, File: path,
	}, true
}

// decodePrometheusCall captures the direct prometheus.NewCounter /
// NewHistogram / NewGauge paths used by packages that need a scalar
// (non-vector) series — policy + schema register their duration
// histograms this way because telemetry.DefineHistogram only returns a
// HistogramVec.
func decodePrometheusCall(fn string, args []ast.Expr, pkg, path string) (metricDecl, bool) {
	var kind string
	switch fn {
	case "NewCounter":
		kind = "counter"
	case "NewHistogram":
		kind = "histogram"
	case "NewGauge":
		kind = "gauge"
	default:
		return metricDecl{}, false
	}
	if len(args) < 1 {
		return metricDecl{}, false
	}
	// Arg is a {Counter,Histogram,Gauge}Opts composite literal carrying
	// Name + Help fields.
	comp, ok := args[0].(*ast.CompositeLit)
	if !ok {
		return metricDecl{}, false
	}
	var name, help string
	for _, e := range comp.Elts {
		kv, ok := e.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch key.Name {
		case "Name":
			name, _ = stringLiteral(kv.Value)
		case "Help":
			help, _ = stringLiteral(kv.Value)
		}
	}
	if name == "" {
		return metricDecl{}, false
	}
	return metricDecl{
		Name: name, Type: kind, Help: help,
		Package: pkg, File: path,
	}, true
}

func stringLiteral(e ast.Expr) (string, bool) {
	l, ok := e.(*ast.BasicLit)
	if !ok || l.Kind != token.STRING {
		return "", false
	}
	v, err := unquote(l.Value)
	if err != nil {
		return "", false
	}
	return v, true
}

// unquote handles both interpreted (`"…"`) and raw (`…`) string literals —
// telemetry call sites use interpreted strings today but raw is allowed.
func unquote(s string) (string, error) {
	if len(s) >= 2 && (s[0] == '`' && s[len(s)-1] == '`') {
		return s[1 : len(s)-1], nil
	}
	return strconvUnquote(s)
}

// strconvUnquote is a local, dependency-light stand-in for strconv.Unquote
// — which would be fine to import, but keeping the dependency set tiny
// makes the generator easier to audit.
func strconvUnquote(s string) (string, error) {
	if len(s) < 2 || s[0] != '"' || s[len(s)-1] != '"' {
		return "", fmt.Errorf("unquote: bad format %q", s)
	}
	// Escaping inside telemetry help strings is limited to \n/\t/\"; a
	// naive Replace is sufficient for the metrics we ship.
	r := strings.NewReplacer(`\"`, `"`, `\n`, "\n", `\t`, "\t", `\\`, `\`)
	return r.Replace(s[1 : len(s)-1]), nil
}

func stringSliceLiteral(e ast.Expr) []string {
	// Accept:
	//   nil
	//   []string{"a", "b"}
	if id, ok := e.(*ast.Ident); ok && id.Name == "nil" {
		return nil
	}
	comp, ok := e.(*ast.CompositeLit)
	if !ok {
		return nil
	}
	var out []string
	for _, elt := range comp.Elts {
		if s, ok := stringLiteral(elt); ok {
			out = append(out, s)
		}
	}
	return out
}

func groupBy[T any, K comparable](items []T, keyFn func(T) K) map[K][]T {
	out := map[K][]T{}
	for _, it := range items {
		k := keyFn(it)
		out[k] = append(out[k], it)
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

func escapePipe(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}

func fatal(f string, args ...any) {
	fmt.Fprintf(os.Stderr, f+"\n", args...)
	os.Exit(1)
}
