// SPDX-License-Identifier: AGPL-3.0-or-later
//go:build ignore

// gen-policy-docs walks the MVP Kind catalogue in pkg/apitypes and renders the
// per-Kind schema summary into docs/reference/policy-schema.md. Each Kind's
// Spec struct is reflected to produce a tabular view of YAML keys, Go types,
// and tag-derived metadata. Run via `make docs-generate`; `make docs-check`
// fails the CI drift gate.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/bino-bi/sluice/pkg/apitypes"
)

const header = `<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Generated by scripts/gen-policy-docs.go — do not edit by hand. -->

# Policy schema

Policy objects are authored as YAML and validated against a JSON Schema
Draft 2020-12 document generated from ` + "`pkg/apitypes`" + `. The schema is
bundled in the binary — ` + "`sluice schema export`" + ` emits a oneOf union
of all registered Kinds; ` + "`--kind`" + ` narrows to one Kind.

## Shared envelope

Every Kind shares the Kubernetes-style envelope:

` + "```yaml" + `
apiVersion: sluice.bino.bi/v1alpha1
kind: <Kind>
metadata:
  name: <unique within Kind>
  namespace: <optional>
  labels: { ... }
  annotations: { ... }
  priority: <int32, higher wins conflict ties>
spec: { ... }
` + "```" + `

Fields under ` + "`spec`" + ` are Kind-specific; the tables below list them.

## Kinds

`

const footer = `
## Regenerating

` + "```bash" + `
make docs-generate
` + "```" + `

Walks ` + "`pkg/apitypes`" + ` via reflection so this page tracks every new
field the moment it lands. The drift gate in ` + "`docs-deploy.yaml`" + ` fails
when the committed file differs from the generator's output.
`

// kindSpec maps each MVP Kind to its Spec type (the body under `spec:`). The
// outer Kind type is always a thin shell around Metadata + TypeMeta + Spec;
// rendering the Spec alone keeps the tables focused on the policy surface.
var kindSpecs = []struct {
	Kind    apitypes.Kind
	Summary string
	Spec    reflect.Type
}{
	{apitypes.KindDataSource, "Attach a catalog to DuckDB.", reflect.TypeFor[apitypes.DataSourceSpec]()},
	{apitypes.KindSubjectBinding, "Map issuer + claim paths onto canonical subject fields.", reflect.TypeFor[apitypes.SubjectBindingSpec]()},
	{apitypes.KindSQLAccessPolicy, "Allow or deny a subject's access to resources.", reflect.TypeFor[apitypes.SQLAccessSpec]()},
	{apitypes.KindRowFilterPolicy, "Inject a WHERE predicate on matching rows.", reflect.TypeFor[apitypes.RowFilterSpec]()},
	{apitypes.KindColumnMaskPolicy, "Replace column values through a mask provider.", reflect.TypeFor[apitypes.ColumnMaskSpec]()},
	{apitypes.KindQueryRejectPolicy, "Reject queries matching a static rule or CEL expression.", reflect.TypeFor[apitypes.QueryRejectSpec]()},
	{apitypes.KindQueryRewritePolicy, "Apply a LIMIT, sample, or timeout transformation.", reflect.TypeFor[apitypes.QueryRewriteSpec]()},
	{apitypes.KindApprovalPolicy, "Require human approval (via webhook) before a matching query runs.", reflect.TypeFor[apitypes.ApprovalSpec]()},
	{apitypes.KindRelationshipPolicy, "Gate access via a ReBAC backend (OpenFGA) relationship check.", reflect.TypeFor[apitypes.RelationshipSpec]()},
	{apitypes.KindDataClassification, "Assign tags to resources so policies can match on tags instead of names.", reflect.TypeFor[apitypes.DataClassificationSpec]()},
	{apitypes.KindAuditSink, "Forward audit records to file / S3 / Postgres / syslog.", reflect.TypeFor[apitypes.AuditSinkSpec]()},
}

func main() {
	out := flag.String("out", "docs/reference/policy-schema.md", "output path")
	check := flag.Bool("check", false, "fail instead of write when output differs")
	flag.Parse()

	var buf bytes.Buffer
	buf.WriteString(header)

	// Summary table first so readers can jump.
	buf.WriteString("| Kind | Summary |\n")
	buf.WriteString("| ---- | ------- |\n")
	for _, ks := range kindSpecs {
		fmt.Fprintf(&buf, "| `%s` | %s |\n", ks.Kind, ks.Summary)
	}
	buf.WriteString("\n")

	// Per-Kind detail sections.
	for _, ks := range kindSpecs {
		fmt.Fprintf(&buf, "### %s\n\n%s\n\n", ks.Kind, ks.Summary)
		buf.WriteString("| Field | Type | Notes |\n")
		buf.WriteString("| ----- | ---- | ----- |\n")
		writeSpecRows(&buf, ks.Spec, "")
		buf.WriteString("\n")
	}

	buf.WriteString(footer)

	abs, err := filepath.Abs(*out)
	if err != nil {
		fatal("resolve path: %v", err)
	}

	if *check {
		cur, err := os.ReadFile(abs)
		if err != nil {
			fatal("read existing: %v", err)
		}
		if !bytes.Equal(cur, buf.Bytes()) {
			fmt.Fprintln(os.Stderr, "policy-schema.md drift: run `make docs-generate`")
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(abs, buf.Bytes(), 0o644); err != nil {
		fatal("write %s: %v", abs, err)
	}
	fmt.Printf("wrote %s (%d kinds)\n", abs, len(kindSpecs))
}

// writeSpecRows walks a struct type and emits one markdown row per exported
// field. Nested structs are flattened with dotted YAML paths so the reader
// sees the full shape at a glance without recursion.
func writeSpecRows(buf *bytes.Buffer, t reflect.Type, prefix string) {
	writeSpecRowsDepth(buf, t, prefix, 0, map[reflect.Type]bool{})
}

func writeSpecRowsDepth(buf *bytes.Buffer, t reflect.Type, prefix string, depth int, seen map[reflect.Type]bool) {
	if depth > 4 {
		return
	}
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct {
		return
	}
	if seen[t] {
		return
	}
	seen[t] = true
	defer delete(seen, t)

	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}

		// Skip inline-embedded meta structs; they are documented in the
		// shared envelope above.
		yamlTag := f.Tag.Get("yaml")
		if strings.Contains(yamlTag, ",inline") {
			continue
		}

		name := yamlName(f)
		if name == "" || name == "-" {
			continue
		}

		path := name
		if prefix != "" {
			path = prefix + "." + name
		}

		typeName := prettyType(f.Type)
		notes := fieldNotes(f)

		fmt.Fprintf(buf, "| `%s` | `%s` | %s |\n", path, typeName, notes)

		// Recurse into non-pointer struct fields whose elements are
		// themselves struct types so readers see nested Spec shapes
		// (e.g. DataSourceSpec.Health).
		inner := f.Type
		if inner.Kind() == reflect.Ptr {
			inner = inner.Elem()
		}
		if inner.Kind() == reflect.Struct && shouldRecurse(inner) {
			writeSpecRowsDepth(buf, inner, path, depth+1, seen)
		}
	}
}

// shouldRecurse returns true when a nested struct belongs to the apitypes
// package — the kinds we own. Stdlib types like time.Duration or pkg/errors
// stay at the summary level.
func shouldRecurse(t reflect.Type) bool {
	return t.PkgPath() == "github.com/bino-bi/sluice/pkg/apitypes"
}

func yamlName(f reflect.StructField) string {
	tag := f.Tag.Get("yaml")
	if tag == "" {
		return strings.ToLower(f.Name)
	}
	parts := strings.Split(tag, ",")
	return parts[0]
}

func fieldNotes(f reflect.StructField) string {
	var parts []string
	yamlTag := f.Tag.Get("yaml")
	if strings.Contains(yamlTag, ",omitempty") {
		parts = append(parts, "optional")
	} else {
		parts = append(parts, "required")
	}

	// Collapse pointer wrappers into "optional" — the ,omitempty marker
	// already communicates that; leave a hint when the field is a slice or
	// map so readers know the cardinality.
	switch f.Type.Kind() {
	case reflect.Slice, reflect.Array:
		parts = append(parts, "list")
	case reflect.Map:
		parts = append(parts, "map")
	}

	return strings.Join(parts, ", ")
}

// prettyType renders a reflect.Type in a way that's readable in a markdown
// table. Pointers are rendered as their element type plus "?"; slices as
// `[]T`; maps as `map[K]V`; typed strings drop the package path.
func prettyType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Ptr:
		return prettyType(t.Elem()) + "?"
	case reflect.Slice, reflect.Array:
		return "[]" + prettyType(t.Elem())
	case reflect.Map:
		return "map[" + prettyType(t.Key()) + "]" + prettyType(t.Elem())
	}
	if t.PkgPath() == "" {
		return t.Name()
	}
	// Strip the package path so `apitypes.Duration` renders as `Duration`.
	if t.Name() != "" {
		return t.Name()
	}
	return t.String()
}

func fatal(f string, args ...any) {
	fmt.Fprintf(os.Stderr, f+"\n", args...)
	os.Exit(1)
}
