// SPDX-License-Identifier: AGPL-3.0-or-later
//go:build ignore

// gen-errorcodes-docs walks pkg/errors.AllCodes() and renders the canonical
// markdown table into docs/reference/error-codes.md. Run via `make
// docs-generate`; the `check-generated-docs.sh` drift gate in CI fails when
// the committed file differs from the generator's output.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/tabwriter"

	pkgerr "github.com/bino-bi/sluice/pkg/errors"
)

const header = `<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Generated by scripts/gen-errorcodes-docs.go — do not edit by hand. -->

# Error codes

` + "`pkg/errors`" + ` defines the stable, machine-readable error catalogue.
Every API response, CLI message, and audit record carries one of these
codes. Codes never change silently; additions require a CHANGELOG entry.

`

const footer = `

## Regenerating

` + "```bash" + `
make docs-generate
` + "```" + `

Walks ` + "`pkg/errors.AllCodes()`" + ` to keep this page in lockstep with
the Go source of truth.
`

func main() {
	out := flag.String("out", "docs/reference/error-codes.md", "output path")
	check := flag.Bool("check", false, "fail instead of write when output differs")
	flag.Parse()

	var buf bytes.Buffer
	buf.WriteString(header)

	tw := tabwriter.NewWriter(&buf, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "| Code\t| HTTP\t| Summary\t|")
	fmt.Fprintln(tw, "| ----\t| ----\t| -------\t|")
	for _, c := range pkgerr.AllCodes() {
		fmt.Fprintf(tw, "| `%s`\t| %d\t| %s\t|\n",
			string(c), pkgerr.Status(c), escapePipe(pkgerr.Message(c)))
	}
	if err := tw.Flush(); err != nil {
		fatal("flush table: %v", err)
	}

	buf.WriteString(footer)

	abs, err := filepath.Abs(*out)
	if err != nil {
		fatal("resolve path: %v", err)
	}

	if *check {
		cur, err := os.ReadFile(abs)
		if err != nil {
			fatal("read existing: %v", err)
		}
		if !bytes.Equal(cur, buf.Bytes()) {
			fmt.Fprintln(os.Stderr, "error-codes.md drift: run `make docs-generate`")
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(abs, buf.Bytes(), 0o644); err != nil {
		fatal("write %s: %v", abs, err)
	}
	fmt.Printf("wrote %s (%d codes)\n", abs, len(pkgerr.AllCodes()))
}

func escapePipe(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}

func fatal(f string, args ...any) {
	fmt.Fprintf(os.Stderr, f+"\n", args...)
	os.Exit(1)
}
